apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: {{ include "kafka-connect.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
  annotations:
  # use-connector-resources configures this KafkaConnect
  # to use KafkaConnector resources to avoid
  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  version: {{ .Values.version }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  bootstrapServers: {{ .Values.bootstrapServers }}
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: {{ .Values.config.replicationFactor }}
    offset.storage.replication.factor: {{ .Values.config.replicationFactor }}
    status.storage.replication.factor: {{ .Values.config.replicationFactor }}
