apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kafka-cluster.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ include "kafka-cluster.name" . }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: {{ .Values.ingress.ip }}
