apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "kafka-cluster.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  kafka:
    replicas: {{ .Values.replicaCount }}
    version: {{ .Values.kafka.version }}
    resources:
{{ toYaml .Values.kafka.resources | indent 6 }}
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 15
      timeoutSeconds: 5
    listeners:
    {{- if .Values.kafka.listeners.plain.enabled }}
    - name: plain
      port: {{ .Values.kafka.listeners.plain.port }}
      type: {{ .Values.kafka.listeners.plain.type }}
      tls: {{ .Values.kafka.listeners.plain.tls }}
    {{- end }}
    {{- if .Values.kafka.listeners.tls.enabled }}
    - name: tls
      port: {{ .Values.kafka.listeners.tls.port }}
      type: {{ .Values.kafka.listeners.tls.type }}
      tls: {{ .Values.kafka.listeners.tls.tls }}
    {{- end }}
    config:
      auto.create.topics.enable: {{ .Values.kafka.config.autoCreateTopicsEnable }}
      offsets.topic.replication.factor: {{ .Values.replicaCount }}
      transaction.state.log.replication.factor: {{ .Values.replicaCount }}
      transaction.state.log.min.isr: 1
    storage:
{{ toYaml .Values.kafka.storage | indent 6 }}
  zookeeper:
    replicas: {{ .Values.replicaCount }}
    resources:
{{ toYaml .Values.zookeeper.resources | indent 6 }}
    storage:
{{ toYaml .Values.zookeeper.storage | indent 6 }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter: {}
