apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-cluster.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
{{ toYaml (merge .Values.service.labels) | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ include "kafka-cluster.name" . }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "kafka-cluster.selectorLabels" . | nindent 4 }}
