apiVersion: v1
data:
  POSTGRES_USER: {{ printf .Values.env.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ printf .Values.env.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_DB: {{ printf .Values.env.POSTGRES_DB | b64enc }}
kind: Secret
metadata:
  name: {{ include "postgres.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
