apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ include "postgres.name" . }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
