apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "schema-registry.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "schema-registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "schema-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "schema-registry.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: {{ include "schema-registry.name" . }}
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:{{ .Values.service.port }}
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: {{ .Values.env.SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
