apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  accessModes:
  - {{ .Values.persistence.accessModes }}
