# Default values for kafka-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

kafka:
  version: 3.4.0
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  listeners:
    plain:
      enabled: true
      port: 9092
      type: internal
      tls: false
    tls:
      enabled: true
      port: 9093
      type: internal
      tls: true
  config:
    autoCreateTopicsEnable: true
  storage:
    type: persistent-claim
    size: 500Mi
    deleteClaim: false

zookeeper:
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  storage:
    type: persistent-claim
    size: 500Mi
    deleteClaim: false

service:
  labels:
    strimzi.io/kind: KafkaExporter
  type: LoadBalancer
  port: 9090
  targetPort: 9094

ingress:
  ip: 127.0.0.1
