apiVersion: v1
stringData:
  password: {{ .Values.env.MONGO_PASSWORD }}
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
