apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb-svc
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: mongodb
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    app: mongodb-svc
    statefulset.kubernetes.io/pod-name: {{ include "mongodb.fullname" . }}-0
