apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-generator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-generator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "data-generator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "data-generator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
          - |
            python src/data_generator.py --db-host mongodb.mongodb.svc.cluster.local
