apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bastion.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bastion.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "bastion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bastion.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sleep", "infinity"]
        resources:
{{ toYaml .Values.resources | indent 10 }}
